version: "3.3"

services:
  regional-sul:
    hostname: regional-sul
    image: base-sistema-regionais:0.0.1
    container_name: container_regional_sul
    ports:
      - "8881:8888"
    environment:
      - REGIAO=Sul
    deploy:
      resources:
        limits:
          memory: 256MB
    restart: always
    #healthcheck:
    #  test: curl -f http://regional-sul:8881/healthcheck || exit 1
    #  interval: 15s
    #  timeout: 10s
    #  retries: 5
    networks:
      - rede-analise-credito

networks:
  rede-analise-credito:
    driver: bridge


# Criando tópico: kafka-console-producer.sh --bootstrap-server 127.0.0.1:9094 --topic solicitacoes_regionais
# Listando tópicos: kafka-topics.sh --list --bootstrap-server localhost:9094
