version: "3.3"

services:
  regional-sul:
    depends_on:
      - kafka
    hostname: regional-sul
    image: base-sistema-regionais:0.0.1
    container_name: container_regional_sul
    ports:
      - "8881:8888"
    environment:
      - REGIAO=Sul
    deploy:
      resources:
        limits:
          memory: 256MB
    restart: always
    healthcheck:
      test: curl -f http://regional-sul:8888/healthcheck || exit 1
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - rede-analise-credito
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: zookeeper
    container_name: container_zookeeper
    ports:
      - "2181:2181"
    networks:
      - rede-analise-credito
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      resources:
        limits:
          memory: 2G
  kafka:
    depends_on:
      - zookeeper
    image: docker.io/bitnami/kafka:3.4
    hostname: kafka
    container_name: container_kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - rede-analise-credito
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  zookeeper_data:
  kafka_data:

networks:
  rede-analise-credito:
    driver: bridge

# Criando tópico: kafka-console-producer.sh --bootstrap-server 127.0.0.1:9094 --topic solicitacoes_regionais
# Listando tópicos: kafka-topics.sh --list --bootstrap-server localhost:9094
# Listando mensagens do tópico: kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9094 --topic solicitacoes_regionais --from-beginning